import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import svg from "esbuild-plugin-svg";
import { copy } from "esbuild-plugin-copy";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const assetForFile = file => ({
  from: [`./${file}`],
  to: [prod ? `./dist/${file}` : `./vault/.obsidian/plugins/poker/${file}`],
});

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  plugins: [
    svg(),
    copy({
      resolveFrom: "cwd",
      assets: [assetForFile("./manifest.json"), assetForFile("./styles.css")],
      watch: true,
    }),
  ],
  outfile: prod ? "dist/main.js" : "vault/.obsidian/plugins/poker/main.js",
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
